{{- if and .Values.acme.enabled .Values.acme.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-acme
  namespace: kube-system
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.acme.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.acme.persistence.size | quote }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
{{- end }}
